# Generated by Django 3.1.7 on 2021-03-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20210307_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
