# Generated by Django 3.1.7 on 2021-03-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210307_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_type',
            new_name='room_types',
        ),
    ]
